### ISSUE TITLE
Improve Reliability of OpenAI Model

### ISSUE THREAD

**Issue by toshan-luktuke** [noobCoderVP/SIH_vikram#12]
Two major action points: 

- [x] Ensure that OpenAI responses always include tags
- [x] Further create a method using regex or string analysis to extract the tags from the received data
- [x] Button click should populate the Legal Services page with the tags received from the AI response

**Comment by sarrah-basta** [comment]
Completed all above tasks linked in following PRs :

1 & 2. https://github.com/noobCoderVP/SIH_vikram/pull/21 
3. https://github.com/noobCoderVP/SIH_vikram/pull/29
